import { db } from "./db";
import {
  products, dealers, operators, posts, subsidies, spareParts, appSettings, users, supplierProfiles, reviews, amcPlans
} from "@shared/schema";
import { scrypt, randomBytes } from "crypto";
import { promisify } from "util";
import { eq } from "drizzle-orm";

const scryptAsync = promisify(scrypt);

async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(16).toString("hex");
  const buf = (await scryptAsync(password, salt, 64)) as Buffer;
  return `${buf.toString("hex")}.${salt}`;
}

export async function seedDatabase() {
  const existingAdmin = await db.select().from(users).where(eq(users.role, "admin")).limit(1);
  if (existingAdmin.length === 0) {
    const hashedPw = await hashPassword("admin123");
    await db.insert(users).values({
      username: "admin",
      password: hashedPw,
      name: "Vipin (Admin)",
      phone: "9090486262",
      role: "admin",
      companyName: "Sai Rolotech",
      location: "Mundka, Delhi",
      state: "Delhi",
      isVerified: true,
    }).onConflictDoNothing();
  }

  const existingSuppliers = await db.select().from(supplierProfiles).limit(1);
  if (existingSuppliers.length === 0) {
    await seedSuppliers();
  }

  const existingAmcPlans = await db.select().from(amcPlans).limit(1);
  if (existingAmcPlans.length === 0) {
    await seedAmcPlans();
  }

  const existingProducts = await db.select().from(products).limit(1);
  if (existingProducts.length > 0) {
    console.log("Database seeded successfully");
    return;
  }

  await db.insert(appSettings).values({
    id: "default",
    companyName: "Sai Rolotech",
    whatsappNumber: "919090486262",
    supportNumber: "919090486262",
    currentCoilRate: "74.50",
    address: "Ground Floor Mdk052, Kh.no.575/1, Udyog Nagar, South Side Industrial Area, Mundka, New Delhi, Delhi - 110041",
  }).onConflictDoNothing();

  await db.insert(products).values([
    {
      name: "Shutter Patti Roll Forming Machine",
      category: "Rolling Shutter",
      subCategory: "Shutter Patti",
      machineType: "Single Machine",
      profileType: "Flat Patti / Curving Patti",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Fully Automatic",
      model: "Advance",
      speed: "30",
      motor: "7.5",
      gauge: "0.40 - 1.20mm",
      stations: "6-13",
      image: "/images/machine-2.png",
      gallery: ["/images/machine-2.png", "/images/machine-3.png"],
      description: "Premium Shutter Patti machine with D3 rollers, CNC machined, 7-inch touch panel, double side gear, FAG bearings. 5-year warranty.",
      estimatedPrice: "8.95",
      rawMaterialWeight: "0.6200",
      isUsed: false,
    },
    {
      name: "Shutter Patti 2-in-1 Heavy Duty",
      category: "Rolling Shutter",
      subCategory: "Shutter Patti",
      machineType: "Two in One Machine",
      profileType: "Flat + Curving Patti",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Fully Automatic",
      model: "Advance",
      speed: "30",
      motor: "10",
      gauge: "0.45 - 0.80mm",
      stations: "8-13",
      image: "/images/machine-2.png",
      gallery: ["/images/machine-2.png", "/images/machine-3.png"],
      description: "Heavy duty shutter patti machine with dual profile capability. Industrial grade with precision cutting and PLC control.",
      estimatedPrice: "18.00",
      rawMaterialWeight: "0.6200",
      isUsed: false,
    },
    {
      name: "Shutter Patti Basic Economy",
      category: "Rolling Shutter",
      subCategory: "Shutter Patti",
      machineType: "Single Machine",
      profileType: "Flat Patti",
      cuttingType: "Punch Scrap",
      decoilerType: "Vertical",
      automation: "Semi-Automatic",
      model: "Basic",
      speed: "20",
      motor: "5",
      gauge: "0.40 - 0.90mm",
      stations: "6-10",
      image: "/images/machine-3.png",
      gallery: ["/images/machine-3.png"],
      description: "Budget-friendly Shutter Patti machine with En8 rollers, lathe machined, chain drive. 1-year warranty. Ideal for startups.",
      estimatedPrice: "2.80",
      rawMaterialWeight: "0.5000",
      isUsed: false,
    },
    {
      name: "Shutter Guide Rail Machine",
      category: "Rolling Shutter",
      subCategory: "Guide Rail",
      machineType: "Single Machine",
      profileType: "U-Channel Guide",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Fully Automatic",
      model: "Medium",
      speed: "25",
      motor: "5",
      gauge: "0.80 - 2.00mm",
      stations: "10-14",
      image: "/images/machine-1.png",
      gallery: ["/images/machine-1.png"],
      description: "Guide rail roll forming machine for rolling shutter track profiles. Heavy gauge capability with precision forming.",
      estimatedPrice: "6.50",
      rawMaterialWeight: "1.2000",
      isUsed: false,
    },
    {
      name: "POP Channel High-Speed Line",
      category: "False Ceiling",
      subCategory: "POP Channel",
      machineType: "Single Machine",
      profileType: "Ceiling Channel",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Fully Automatic",
      model: "Advance",
      speed: "45",
      motor: "7.5",
      gauge: "0.40 - 0.70mm",
      stations: "8-12",
      image: "/images/machine-1.png",
      gallery: ["/images/machine-1.png", "/images/machine-2.png"],
      description: "Ultra fast POP channel production line with PLC control. Designed for heavy industrial use with precision forming rollers.",
      estimatedPrice: "13.50",
      rawMaterialWeight: "0.4500",
      isUsed: false,
    },
    {
      name: "Main Channel & Furring 2-in-1",
      category: "False Ceiling",
      subCategory: "Main Channel",
      machineType: "Two in One Machine",
      profileType: "Main Channel + Furring Channel",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Fully Automatic",
      model: "Advance",
      speed: "35",
      motor: "7.5",
      gauge: "0.35 - 0.70mm",
      stations: "10-14",
      image: "/images/machine-1.png",
      gallery: ["/images/machine-1.png", "/images/machine-3.png"],
      description: "Dual profile false ceiling machine producing main channel and furring channel. High-speed production with auto stacking.",
      estimatedPrice: "16.00",
      rawMaterialWeight: "0.3500",
      isUsed: false,
    },
    {
      name: "T-Grid Automatic Production Line",
      category: "False Ceiling",
      subCategory: "T-Grid",
      machineType: "Single Machine",
      profileType: "Main Tee / Cross Tee",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Fully Automatic",
      model: "Advance",
      speed: "35",
      motor: "7.5",
      gauge: "0.30 - 0.50mm",
      stations: "12-16",
      image: "/images/machine-1.png",
      gallery: ["/images/machine-1.png"],
      description: "High-speed T-Grid production line for suspended ceiling systems. Fully automatic with PLC control and auto punching.",
      estimatedPrice: "15.50",
      rawMaterialWeight: "0.2800",
      isUsed: false,
    },
    {
      name: "False Ceiling 10-Profile Setup",
      category: "False Ceiling",
      subCategory: "Multi Profile",
      machineType: "Multi Profile Setup",
      profileType: "POP + Main + Furring + T-Grid + Angle",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal (Advanced)",
      automation: "Fully Automatic",
      model: "Advance",
      speed: "30",
      motor: "15",
      gauge: "0.30 - 0.70mm",
      stations: "16-20",
      image: "/images/machine-1.png",
      gallery: ["/images/machine-1.png", "/images/machine-2.png", "/images/machine-3.png"],
      description: "Complete false ceiling production setup supporting 10 distinct profiles in a single 2-in-1 layout. Full factory solution.",
      estimatedPrice: "45.00",
      rawMaterialWeight: "0.4500",
      isUsed: false,
    },
    {
      name: "C-Channel & Stud 3-in-1",
      category: "Drywall & Partition",
      subCategory: "C-Channel / Stud",
      machineType: "Three in One Machine",
      profileType: "C-Channel + Stud + Track",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Semi-Automatic",
      model: "Medium",
      speed: "25",
      motor: "5",
      gauge: "0.35 - 0.60mm",
      stations: "10-14",
      image: "/images/machine-3.png",
      gallery: ["/images/machine-3.png", "/images/machine-1.png"],
      description: "Versatile drywall profile machine producing C-Channel, track, and stud profiles in a single setup. Interchangeable rollers.",
      estimatedPrice: "11.00",
      rawMaterialWeight: "0.3800",
      isUsed: false,
    },
    {
      name: "Partition Section Machine",
      category: "Drywall & Partition",
      subCategory: "Partition Section",
      machineType: "Single Machine",
      profileType: "Partition Wall Section",
      cuttingType: "Punch Scrap",
      decoilerType: "Horizontal",
      automation: "Semi-Automatic",
      model: "Basic",
      speed: "20",
      motor: "5",
      gauge: "0.40 - 0.80mm",
      stations: "8-12",
      image: "/images/machine-3.png",
      gallery: ["/images/machine-3.png"],
      description: "Partition section roll forming machine for wall framing profiles. Budget-friendly for small-scale production.",
      estimatedPrice: "5.50",
      rawMaterialWeight: "0.4500",
      isUsed: false,
    },
    {
      name: "Z-Purlin Roll Forming Machine",
      category: "Structural",
      subCategory: "Z-Purlin",
      machineType: "Single Machine",
      profileType: "Z-Section Purlin",
      cuttingType: "Hydraulic Cut",
      decoilerType: "Horizontal (5 Ton)",
      automation: "Fully Automatic",
      model: "Advance",
      speed: "15",
      motor: "15",
      gauge: "1.20 - 3.00mm",
      stations: "16-22",
      image: "/images/machine-1.png",
      gallery: ["/images/machine-1.png", "/images/machine-2.png"],
      description: "Heavy-duty Z-Purlin machine for structural steel applications. Hydraulic cutting, PLC control, variable speed drive.",
      estimatedPrice: "22.00",
      rawMaterialWeight: "2.5000",
      isUsed: false,
    },
    {
      name: "C-Purlin Roll Forming Machine",
      category: "Structural",
      subCategory: "C-Purlin",
      machineType: "Single Machine",
      profileType: "C-Section Purlin",
      cuttingType: "Hydraulic Cut",
      decoilerType: "Horizontal (5 Ton)",
      automation: "Fully Automatic",
      model: "Advance",
      speed: "15",
      motor: "15",
      gauge: "1.20 - 3.00mm",
      stations: "18-24",
      image: "/images/machine-1.png",
      gallery: ["/images/machine-1.png"],
      description: "C-Purlin production machine for pre-engineered building structures. Auto size changeover with servo punching.",
      estimatedPrice: "25.00",
      rawMaterialWeight: "2.5000",
      isUsed: false,
    },
    {
      name: "Door Frame Roll Forming Machine",
      category: "Door & Window",
      subCategory: "Door Frame",
      machineType: "Single Machine",
      profileType: "Steel Door Chaukhat",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Fully Automatic",
      model: "Medium",
      speed: "20",
      motor: "7.5",
      gauge: "0.60 - 1.20mm",
      stations: "12-16",
      image: "/images/machine-2.png",
      gallery: ["/images/machine-2.png"],
      description: "Door frame (chaukhat) roll forming machine for steel door frames. Multiple profile sizes with quick changeover.",
      estimatedPrice: "12.00",
      rawMaterialWeight: "0.8000",
      isUsed: false,
    },
    {
      name: "Window Section Machine",
      category: "Door & Window",
      subCategory: "Window Section",
      machineType: "Single Machine",
      profileType: "Window Z-Section",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Semi-Automatic",
      model: "Medium",
      speed: "20",
      motor: "5",
      gauge: "0.50 - 1.00mm",
      stations: "10-14",
      image: "/images/machine-3.png",
      gallery: ["/images/machine-3.png"],
      description: "Window section roll forming machine for steel window profiles. Precise forming with consistent dimensions.",
      estimatedPrice: "8.50",
      rawMaterialWeight: "0.6000",
      isUsed: false,
    },
    {
      name: "Roofing Sheet Machine (Trapezoidal)",
      category: "Roofing & Cladding",
      subCategory: "Trapezoidal Sheet",
      machineType: "Single Machine",
      profileType: "Trapezoidal Roofing Profile",
      cuttingType: "Hydraulic Cut",
      decoilerType: "Horizontal (5 Ton)",
      automation: "Fully Automatic",
      model: "Advance",
      speed: "12",
      motor: "10",
      gauge: "0.35 - 0.80mm",
      stations: "16-20",
      image: "/images/machine-1.png",
      gallery: ["/images/machine-1.png", "/images/machine-2.png"],
      description: "Trapezoidal roofing sheet production machine. Auto length cut with counter. High precision profile forming.",
      estimatedPrice: "18.00",
      rawMaterialWeight: "0.5000",
      isUsed: false,
    },
    {
      name: "Corrugated Sheet Machine",
      category: "Roofing & Cladding",
      subCategory: "Corrugated Sheet",
      machineType: "Single Machine",
      profileType: "Corrugated Wave Profile",
      cuttingType: "Hydraulic Cut",
      decoilerType: "Horizontal (3 Ton)",
      automation: "Fully Automatic",
      model: "Medium",
      speed: "15",
      motor: "7.5",
      gauge: "0.30 - 0.60mm",
      stations: "12-14",
      image: "/images/machine-2.png",
      gallery: ["/images/machine-2.png"],
      description: "Corrugated sheet forming machine for roofing and cladding applications. Standard sinusoidal profile.",
      estimatedPrice: "10.00",
      rawMaterialWeight: "0.4000",
      isUsed: false,
    },
    {
      name: "Solar Panel Mounting Channel Machine",
      category: "Solar & Infrastructure",
      subCategory: "Solar Structure",
      machineType: "Single Machine",
      profileType: "Solar Mounting Channel",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Fully Automatic",
      model: "Medium",
      speed: "25",
      motor: "5",
      gauge: "0.80 - 2.00mm",
      stations: "10-14",
      image: "/images/machine-3.png",
      gallery: ["/images/machine-3.png"],
      description: "Solar panel mounting structure channel machine. Produces mounting rails for solar installations. Growing demand sector.",
      estimatedPrice: "9.50",
      rawMaterialWeight: "1.2000",
      isUsed: false,
    },
    {
      name: "Highway Guard Rail Machine",
      category: "Solar & Infrastructure",
      subCategory: "Guard Rail",
      machineType: "Single Machine",
      profileType: "W-Beam Guard Rail",
      cuttingType: "Hydraulic Cut",
      decoilerType: "Horizontal (10 Ton)",
      automation: "Fully Automatic",
      model: "Advance",
      speed: "8",
      motor: "25",
      gauge: "2.50 - 4.00mm",
      stations: "20-28",
      image: "/images/machine-1.png",
      gallery: ["/images/machine-1.png"],
      description: "Heavy-duty highway guard rail (W-Beam) forming machine. Government approved specifications for crash barriers.",
      estimatedPrice: "55.00",
      rawMaterialWeight: "3.5000",
      isUsed: false,
    },
    {
      name: "2021 POP Channel Machine",
      category: "False Ceiling",
      subCategory: "POP Channel",
      machineType: "Single Machine",
      profileType: "Ceiling Channel",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Fully Automatic",
      model: "Medium",
      speed: "35",
      motor: "5",
      gauge: "0.40 - 0.60mm",
      stations: "10",
      image: "/images/machine-2.png",
      description: "Well maintained POP Channel machine. Working perfectly. Single owner.",
      estimatedPrice: "5.50",
      isUsed: true,
      condition: "Excellent",
      location: "Ghaziabad, UP",
      yearOfPurchase: "2021",
    },
    {
      name: "2019 Shutter Patti Semi-Auto",
      category: "Rolling Shutter",
      subCategory: "Shutter Patti",
      machineType: "Single Machine",
      profileType: "Flat Patti",
      cuttingType: "Punch Scrap",
      decoilerType: "Vertical",
      automation: "Semi-Automatic",
      model: "Basic",
      speed: "20",
      motor: "3",
      gauge: "0.45 - 0.70mm",
      stations: "8",
      image: "/images/machine-3.png",
      description: "Good condition semi-automatic shutter patti machine. Ready for immediate production.",
      estimatedPrice: "3.20",
      isUsed: true,
      condition: "Good",
      location: "Delhi",
      yearOfPurchase: "2019",
    },
    {
      name: "2022 C-Channel Machine",
      category: "Drywall & Partition",
      subCategory: "C-Channel / Stud",
      machineType: "Single Machine",
      profileType: "C-Channel",
      cuttingType: "Ultra Cut",
      decoilerType: "Horizontal",
      automation: "Semi-Automatic",
      model: "Medium",
      speed: "22",
      motor: "5",
      gauge: "0.40 - 0.60mm",
      stations: "10",
      image: "/images/machine-3.png",
      description: "2022 model C-Channel machine in excellent condition. Very low usage, like new. Buyer can inspect.",
      estimatedPrice: "4.80",
      isUsed: true,
      condition: "Excellent",
      location: "Noida, UP",
      yearOfPurchase: "2022",
    },
  ]);

  await db.insert(dealers).values([
    {
      name: "Aggarwal Steel Traders",
      phone: "9876543210",
      location: "Loha Mandi, Delhi",
      state: "Delhi",
      rating: "4.8",
      ratingCount: 156,
      dailyRate: "72.50",
      rateGauge: "0.50mm",
      gstNo: "07AAAAA0000A1Z5",
      address: "Shop No. 12, Steel Market, Loha Mandi, Wazirpur Industrial Area, New Delhi - 110052",
    },
    {
      name: "Sharma Iron & Steel",
      phone: "9887654321",
      location: "Mundka, Delhi",
      state: "Delhi",
      rating: "4.5",
      ratingCount: 89,
      dailyRate: "73.00",
      rateGauge: "0.50mm",
      gstNo: "07BBBBB0000B1Z5",
      address: "B-42, Mundka Industrial Area, New Delhi - 110041",
    },
    {
      name: "Gupta Steels Pvt Ltd",
      phone: "9998765432",
      location: "Ghaziabad, UP",
      state: "Uttar Pradesh",
      rating: "4.6",
      ratingCount: 203,
      dailyRate: "71.80",
      rateGauge: "0.50mm",
      gstNo: "09CCCCC0000C1Z5",
      address: "Plot 78, UPSIDC Industrial Area, Ghaziabad - 201009",
    },
    {
      name: "Rajdhani Metal Corporation",
      phone: "9776543210",
      location: "Faridabad, Haryana",
      state: "Haryana",
      rating: "4.3",
      ratingCount: 67,
      dailyRate: "74.00",
      rateGauge: "0.50mm",
      address: "Sector 24, Faridabad Industrial Area, Haryana - 121005",
    },
  ]);

  await db.insert(operators).values([
    {
      name: "Suresh Kumar",
      phone: "9123456789",
      experience: "5 Years",
      location: "Delhi NCR",
      specialization: "POP Channel & False Ceiling Machines",
    },
    {
      name: "Rajesh Yadav",
      phone: "9234567890",
      experience: "8 Years",
      location: "Ghaziabad",
      specialization: "Shutter Patti & Roll Forming",
    },
    {
      name: "Mohammad Arif",
      phone: "9345678901",
      experience: "3 Years",
      location: "Noida",
      specialization: "C-Channel & Drywall Machines",
    },
  ]);

  await db.insert(posts).values([
    {
      type: "image",
      caption: "Full Project Setup for False Ceiling profiles. This installation supports 10 distinct profiles in a single 2-in-1 layout.",
      author: "Sai Rolotech Official",
      likes: 452,
      images: ["/images/machine-1.png", "/images/factory.png"],
      isApproved: true,
    },
    {
      type: "image",
      caption: "Heavy Duty Shutter Patti Machine in action. Precision engineering at its best. Our latest model delivers 30m/min speed.",
      author: "Sai Rolotech Factory",
      likes: 89,
      images: ["/images/machine-2.png"],
      isApproved: true,
    },
    {
      type: "image",
      caption: "New C-Channel production line installed at client site in Rajasthan. Delivering excellence across India.",
      author: "Sai Rolotech Official",
      likes: 234,
      images: ["/images/machine-3.png", "/images/parts.png"],
      isApproved: true,
    },
    {
      type: "image",
      caption: "Quality check in progress. Every machine goes through 47-point inspection before delivery. No compromise on quality.",
      author: "Sai Rolotech QC Team",
      likes: 167,
      images: ["/images/parts.png"],
      isApproved: true,
    },
  ]);

  await db.insert(subsidies).values([
    {
      name: "PMEGP - Prime Minister's Employment Generation Programme",
      description: "Government subsidy for setting up new micro enterprises in manufacturing sector. Get up to 35% subsidy on project cost.",
      eligibility: "Any individual above 18 years. 8th pass for manufacturing projects above Rs 10 lakh. Self Help Groups included.",
      subsidy: "Up to 35% of project cost (max Rs 25 Lakh for manufacturing)",
      applyUrl: "https://www.kviconline.gov.in/pmegpeportal/jsp/pmegponline.jsp",
      state: "All India",
      category: "Central Government",
    },
    {
      name: "CLCSS - Credit Linked Capital Subsidy Scheme",
      description: "Technology upgradation scheme for MSMEs. Get 15% capital subsidy on institutional finance for technology upgradation.",
      eligibility: "Existing SSI/MSME units. Must be registered under MSME Act.",
      subsidy: "15% capital subsidy (max Rs 15 Lakh)",
      applyUrl: "https://msme.gov.in",
      state: "All India",
      category: "Central Government",
    },
    {
      name: "UP MSME Loan Scheme",
      description: "Uttar Pradesh state scheme for setting up manufacturing units. Special benefits for SC/ST entrepreneurs.",
      eligibility: "UP domicile. Must set up unit in UP. Priority for SC/ST/OBC.",
      subsidy: "25% margin money subsidy (max Rs 5 Lakh) + interest subsidy",
      state: "Uttar Pradesh",
      category: "State Government",
    },
    {
      name: "Stand-Up India Scheme",
      description: "Bank loans between Rs 10 lakh and Rs 1 Crore for SC/ST and women entrepreneurs for greenfield enterprises.",
      eligibility: "SC/ST or Women entrepreneur. Must be a greenfield enterprise. Age above 18 years.",
      subsidy: "Composite loan Rs 10 Lakh to Rs 1 Crore with relaxed terms",
      applyUrl: "https://www.standupmitra.in",
      state: "All India",
      category: "Central Government",
    },
    {
      name: "MUDRA Yojana",
      description: "Micro Units Development & Refinance Agency loans for small manufacturing units. Three categories: Shishu, Kishore, Tarun.",
      eligibility: "Any Indian citizen with business plan for manufacturing/service unit.",
      subsidy: "Loans up to Rs 10 Lakh without collateral. Shishu (up to 50K), Kishore (50K-5L), Tarun (5L-10L)",
      applyUrl: "https://www.mudra.org.in",
      state: "All India",
      category: "Central Government",
    },
  ]);

  await db.insert(spareParts).values([
    { name: "High-Tensile Cutter Blade", price: "4,500", image: "/images/parts.png", category: "Cutter" },
    { name: "Precision Forming Roller Set", price: "12,000", image: "/images/parts.png", category: "Roller" },
    { name: "Delta PLC CPU Module", price: "8,500", image: "/images/parts.png", category: "Electrical" },
    { name: "Heavy Duty Bearing (6205)", price: "850", image: "/images/parts.png", category: "Mechanical" },
    { name: "Hydraulic Cutting Cylinder", price: "15,000", image: "/images/parts.png", category: "Hydraulic" },
    { name: "Main Drive Shaft Assembly", price: "22,000", image: "/images/parts.png", category: "Mechanical" },
  ]);

  console.log("Database seeded successfully");
}

async function seedSuppliers() {
  const supplierData = await db.insert(supplierProfiles).values([
    {
      companyName: "Sai Rolotech Industries",
      ownerName: "Vipin Gupta",
      gstNo: "09AABCS1234A1Z5",
      businessType: "Manufacturer",
      establishedYear: "2015",
      totalEmployees: "25-50",
      factoryAddress: "Ground Floor Mdk052, Kh.no.575/1, Udyog Nagar, South Side Industrial Area, Mundka",
      state: "Delhi",
      city: "New Delhi",
      pincode: "110041",
      phone: "9090486262",
      email: "sairolotech@gmail.com",
      whatsapp: "919090486262",
      description: "Leading manufacturer of roll forming machines, POP channel machines, shutter patti machines, and false ceiling profile machines. 10+ years of expertise in industrial machine manufacturing.",
      specialization: "Roll Forming Machines, POP Channel, Shutter Patti, False Ceiling",
      serviceArea: "Pan India",
      deliveryCapability: "All India delivery with installation support",
      rating: "4.8",
      ratingCount: 156,
      isGstVerified: true,
      isPremium: true,
      isVerified: true,
      isTopRated: true,
      isFastResponder: true,
      responseTime: "Under 1 hour",
    },
    {
      companyName: "Bharat Roll Forming",
      ownerName: "Rakesh Sharma",
      gstNo: "07AABCB5678B1Z5",
      businessType: "Manufacturer",
      establishedYear: "2012",
      totalEmployees: "50-100",
      factoryAddress: "B-78, Industrial Area, Mundka",
      state: "Delhi",
      city: "New Delhi",
      pincode: "110041",
      phone: "9876012345",
      email: "bharatrollforming@gmail.com",
      whatsapp: "919876012345",
      description: "Manufacturer of high-speed roll forming lines, C-purlin machines, and Z-purlin machines for construction industry.",
      specialization: "C-Purlin, Z-Purlin, Roof Sheet Machines",
      serviceArea: "North India",
      deliveryCapability: "North India with 7-day delivery",
      rating: "4.5",
      ratingCount: 89,
      isGstVerified: true,
      isPremium: false,
      isVerified: true,
      isTopRated: false,
      isFastResponder: true,
      responseTime: "Under 2 hours",
    },
    {
      companyName: "Gupta Engineering Works",
      ownerName: "Amit Gupta",
      gstNo: "09AABCG9012C1Z5",
      businessType: "Manufacturer",
      establishedYear: "2018",
      totalEmployees: "10-25",
      factoryAddress: "Plot 45, UPSIDC Industrial Area",
      state: "Uttar Pradesh",
      city: "Noida",
      pincode: "201301",
      phone: "9988776655",
      email: "guptaengg@gmail.com",
      whatsapp: "919988776655",
      description: "Specialist in drywall profile machines and light gauge steel framing machines. Custom machine development available.",
      specialization: "Drywall Machines, Light Gauge Steel, Custom Solutions",
      serviceArea: "Delhi NCR",
      deliveryCapability: "Delhi NCR same-day, rest of India 10 days",
      rating: "4.2",
      ratingCount: 45,
      isGstVerified: true,
      isPremium: false,
      isVerified: false,
      isTopRated: false,
      isFastResponder: false,
      responseTime: "Under 4 hours",
    },
    {
      companyName: "Rajdhani Industrial Solutions",
      ownerName: "Sunil Aggarwal",
      businessType: "Trader",
      establishedYear: "2020",
      totalEmployees: "5-10",
      factoryAddress: "Sector 24, Industrial Area",
      state: "Haryana",
      city: "Faridabad",
      pincode: "121005",
      phone: "9112233445",
      whatsapp: "919112233445",
      description: "Trading and supply of used roll forming machines and spare parts. Buy-sell-exchange platform for industrial machinery.",
      specialization: "Used Machines, Spare Parts, Machine Exchange",
      serviceArea: "Haryana, Delhi NCR",
      deliveryCapability: "Local pickup or transport arranged",
      rating: "3.8",
      ratingCount: 23,
      isGstVerified: false,
      isPremium: false,
      isVerified: false,
      isTopRated: false,
      isFastResponder: false,
      responseTime: "Same day",
    },
    {
      companyName: "Maharashtra Steel Machines Pvt Ltd",
      ownerName: "Pravin Patil",
      gstNo: "27AABCM3456D1Z5",
      businessType: "Manufacturer",
      establishedYear: "2010",
      totalEmployees: "100+",
      factoryAddress: "Plot 112, MIDC Industrial Area, Bhosari",
      state: "Maharashtra",
      city: "Pune",
      pincode: "411026",
      phone: "9823456789",
      email: "msmachines@gmail.com",
      whatsapp: "919823456789",
      description: "Large-scale manufacturer of corrugated sheet machines, trapezoidal sheet machines, and roof tile forming machines. ISO 9001 certified.",
      specialization: "Corrugated Sheet, Trapezoidal, Roof Tile Machines",
      serviceArea: "Pan India + Export",
      deliveryCapability: "Pan India with installation team",
      rating: "4.6",
      ratingCount: 203,
      isGstVerified: true,
      isPremium: true,
      isVerified: true,
      isTopRated: true,
      isFastResponder: true,
      responseTime: "Under 30 minutes",
    },
  ]).returning();

  for (const supplier of supplierData) {
    const reviewsData = [
      { reviewerName: "Rajesh Kumar", rating: 5, comment: "Excellent quality machines. Very professional team.", isVerifiedBuyer: true },
      { reviewerName: "Mahesh Yadav", rating: 4, comment: "Good service and timely delivery. Recommended.", isVerifiedBuyer: true },
      { reviewerName: "Ankit Singh", rating: 4, comment: "Decent machines at competitive prices.", isVerifiedBuyer: false },
    ];
    for (const r of reviewsData.slice(0, supplier.isPremium ? 3 : 2)) {
      await db.insert(reviews).values({
        supplierId: supplier.id,
        reviewerName: r.reviewerName,
        rating: r.rating,
        comment: r.comment,
        isVerifiedBuyer: r.isVerifiedBuyer,
        isApproved: true,
      });
    }
  }
  console.log("Supplier seed data inserted");
}

async function seedAmcPlans() {
  await db.insert(amcPlans).values([
    {
      name: "Basic AMC",
      tier: "basic",
      visitsPerYear: 2,
      price1Year: "15,000",
      price2Year: "25,000",
      features: [
        "2 preventive maintenance visits per year",
        "Phone & WhatsApp support (business hours)",
        "10% discount on spare parts",
        "Machine health report after each visit",
        "Basic troubleshooting guidance",
      ],
      phoneSupport: true,
      prioritySupport: false,
      emergencySupport: false,
      freeLabor: false,
      spareParts: "10% discount",
      dedicatedPartner: false,
      isPopular: false,
    },
    {
      name: "Standard AMC",
      tier: "standard",
      visitsPerYear: 4,
      price1Year: "25,000",
      price2Year: "42,000",
      features: [
        "4 preventive maintenance visits per year",
        "Priority phone & WhatsApp support",
        "Minor spare parts included (bearings, belts)",
        "48-hour response time guarantee",
        "Detailed machine performance report",
        "Operator training during visits",
        "15% discount on major spare parts",
      ],
      phoneSupport: true,
      prioritySupport: true,
      emergencySupport: false,
      freeLabor: false,
      spareParts: "Minor parts included + 15% off major",
      dedicatedPartner: false,
      isPopular: true,
    },
    {
      name: "Premium AMC",
      tier: "premium",
      visitsPerYear: 4,
      price1Year: "45,000",
      price2Year: "78,000",
      features: [
        "Quarterly comprehensive maintenance",
        "24/7 emergency support with 4-hour response",
        "All labor charges included",
        "Dedicated service partner assigned",
        "Free minor & major spare parts (up to ₹5,000/visit)",
        "Priority scheduling for all visits",
        "Monthly machine health check calls",
        "Annual machine calibration included",
        "Operator re-training sessions",
      ],
      phoneSupport: true,
      prioritySupport: true,
      emergencySupport: true,
      freeLabor: true,
      spareParts: "Free parts up to ₹5,000/visit",
      dedicatedPartner: true,
      isPopular: false,
    },
  ]);
  console.log("AMC plans seed data inserted");
}
